services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: otp-container

    ports:
      - "8000:8000"

    volumes:
      - ./keys:/app/keys
      - ./data:/app/data
      - ./cron:/app/cron

    environment:
      TZ: UTC

    restart: unless-stopped
